# Generated by Django 3.1.6 on 2021-03-16 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created', 'category')},
        ),
    ]
