# Generated by Django 3.1.6 on 2021-03-16 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0002_auto_20210316_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
