# Generated by Django 3.1.6 on 2021-03-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='package',
            field=models.CharField(blank=True, choices=[('Bigginer', 'Bigginer'), ('Standard', 'Standard'), ('Platinum', 'Platinum'), ('Ruby', 'Ruby'), ('Gold', 'Gold'), ('Eminent', 'Eminent')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='price',
            field=models.CharField(blank=True, choices=[('3,000', '3,000'), ('5,000', '5,000'), ('10,000', '10,000'), ('20,000', '20,000'), ('50,000', '50,000'), ('100,000', '100,000')], max_length=50, null=True),
        ),
    ]
