# Generated by Django 3.1.6 on 2021-03-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210316_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
